### ISSUE TITLE
Ошибка при установке имеющегося проекта на базе коробочной версии Directum RX 4.5.49.0

### ISSUE THREAD

**Issue by MegaDoge1337** [DirectumCompany/rx-manage-applied-projects#23]
При подготовке уже имеющегося проекта на базе коробки RX 4.5.49.0 DDS начинает затирать метаданные. Не могу понять причину такого поведения
![i1](https://github.com/DirectumCompany/rx-manage-applied-projects/assets/56873848/8de0b4cc-78a7-4551-9065-a16645f91938)
![i2](https://github.com/DirectumCompany/rx-manage-applied-projects/assets/56873848/dd11e204-d04f-4f15-ae71-765ed39a8140)

Содержимое yml-файла проекта
```yml
# ключевые параметры проекта
variables:
    # Назначение проекта
    purpose: 'DirectumRX 4.5.49.0 (Тут название проекта)'
    # БД проекта
    database: 'rx4549_ProjectName'
    # Домашняя директория, относительно которой хранятся все данные сервисов.
    # Используется только в конфигурационном файле.
    home_path: 'C:\rx\4549\d\ProjectName'
    # Корневой каталог c репозиториями проекта
    home_path_src: 'C:\rx\4549\s\'
# репозитории
services_config:
    DevelopmentStudio:
        REPOSITORIES:
            repository:
            -   '@folderName': 'DirectumRX-4.5-ProjectName-Work'
                '@solutionType': 'Work'
                '@url': 'http://git.server/a.pankrashov/DirectumRX-4.5-ProjectName-Work.git'
            -   '@folderName': 'DirectumRX-4.5-ProjectName-Base'
                '@solutionType': 'Base'
                '@url': 'http://git.server/a.pankrashov/DirectumRX-4.5-ProjectName-Base.git'
```

Установка производилась в соответствии с видео-инструкцией на Youtube
Из гипотез пробовал удалить папку .sds, отменить изменения и собрать проект ещё раз, но ситуация никак не меняется
